django/project/urls.py
from django.conf.urls import url, include
from django.contrib   import admin
from straits          import views

urlpatterns_api = [

    url( r'^(?P<resource>.+?)/(?P<resource_id>(\d)+)/(?P<sub_resource>.+?)/(?P<sub_resource_id>(\d)+)/',
        views.Api.as_view(),
        name='api',
    ),
    url( r'^(?P<resource>.+?)/(?P<resource_id>(\d)+)/(?P<sub_resource>.+?)/',
        views.Api.as_view(),
        name='api',
    ),
    url( r'^(?P<resource>temp)/(?P<template_id>(\d)+)/',
        views.Api.as_view(),
        name='api_template',
    ),

]
# /api/templates/sect/${sectionId}/quests/

urlpatterns = [
    url( r'^admin/',            admin.site.urls),

    url( r'^api/templates/',    include( urlpatterns_api ) ),

    url( r'(\d+)/',             views.Index.as_view(), name='index' ),
    url( r'',                   views.Index.as_view(), name='index' ),


    url( r'^all-templates/',    views.Index.as_view(), name='all-templates' ),
    url( r'^ajax-versions/',    views.Index.as_view(), name='ajax-versions' ),
]

django/straits/models.py
# -*- coding: utf-8 -*-
from __future__                         import unicode_literals
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db                          import models


def get_profile_choices():
    return Profile.objects.values_list( 'pk', 'user__username' )

def get_contenttype_company():
    return ContentType.objects.get( model='company' )

def get_contenttype_profile():
    return ContentType.objects.get( model='profile' )


class Company( models.Model ):
    name        = models.CharField( max_length=100, unique=True )
    country     = models.CharField( max_length=100, unique=True )
    testobject  = GenericRelation(
        'TestObject',
        related_query_name='company_objects',
        content_type_field='company_content_type',
        object_id_field='company_object_id',
    )

    def __unicode__( self ):
        return self.name

    class Meta:
        verbose_name_plural = 'Companies'


class Profile( models.Model ):
    user        = models.OneToOneField( 'auth.User', on_delete=models.PROTECT )
    company     = models.ForeignKey( 'Company', on_delete=models.PROTECT )
    testobject  = GenericRelation(
        'TestObject',
        related_query_name='profile_objects',
        content_type_field='profile_content_type',
        object_id_field='profile_object_id',
    )

    def __unicode__( self ):
        return self.user.username


class TestObject( models.Model ):
    profile_content_type    = models.ForeignKey(
        'contenttypes.ContentType',
        on_delete=models.PROTECT,
        related_name='+',
        limit_choices_to={ 'model': 'profile' },
        default=get_contenttype_profile,
    )
    profile_object_id       = models.PositiveIntegerField( verbose_name='Profile' )
    profile_content_object  = GenericForeignKey( 'profile_content_type', 'profile_object_id' )
    company_content_type    = models.ForeignKey(
        'contenttypes.ContentType',
        on_delete=models.PROTECT,
        related_name='+',
        limit_choices_to={ 'model': 'company' },
        default=get_contenttype_company,
    )
    company_object_id       = models.PositiveIntegerField( verbose_name='Company' )
    company_content_object  = GenericForeignKey( 'company_content_type', 'company_object_id' )


    def __unicode__( self ):
        return '%s:%s' % ( self.profile.user.username, self.company.name )

    @property
    def profile( self ):
        return self.profile_content_type.get_object_for_this_type( pk=self.profile_object_id )

    @property
    def company( self ):
        return self.company_content_type.get_object_for_this_type( pk=self.company_object_id )

    class Meta:
        unique_together = [
            'profile_content_type',
            'profile_object_id',
            'company_content_type',
            'company_object_id',
        ]

django/straits/views.py
# -*- coding: utf-8 -*-
from __future__         import unicode_literals
from django.http        import HttpResponse, JsonResponse
from django.shortcuts   import render, redirect
from django.views       import View
import logging
import requests

class Index( View ):

    def get( self, request, t_id=0, *args, **kwargs ):
        cversion = { 'order': 2 }
        if not t_id:
            return redirect( 'index', 6 )
        t_name = 'Test'
        return render( request, 'edit_template/index.html', locals() )


class Api( View ):
    ''' API proxy to workaround CORS '''

    base_url = 'https://www.dataprotectionmgmt.com/api/templates/'
    headers  = {
        'Authorization': 'Token f203975b6a893f933e3a29caf175a5e2a27a4bcc',
    }

    def get( self, request, **kwargs ):
        url = self.get_url( request, **kwargs )
        response = requests.get( url, headers=self.headers )
        return JsonResponse( response.json(), safe=False )


    def get_url( self, request, resource, resource_id=None, sub_resource=None, sub_resource_id=None ):
        url = '%s%s/' % ( self.base_url, resource )

        if resource_id:
            url = '%s%s/' % ( url, resource_id )

            if sub_resource:
                url = '%s%s/' % ( url, sub_resource )
                if sub_resource_id:
                    url = '%s%s/' % ( url, sub_resource_id )

        version = request.GET.get( 'version', 2 )
        url = '%s?version=%s' % ( url, version )
        return url

django/straits/templates/edit_template/index.html
{# extends site_details.template #}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/79dad4fdc0.css">

    <style>
        body {
            background-color: #eff3f8;
            font-size: 1.25em;
        }
        .portlet {
            background-color: white;
            padding: 1.5em;
            margin-bottom: 3em;
            border: solid thin lightgrey;
            box-shadow: 0 4px 8px 0 grey;
        }
        .margin-top-20 {
            margin-top: 1em;
        }

        .s-title {
            margin: 5px 0;
        }

        .panel-title {
            line-height: 1.5em;
        }

        .btn-middle {
            margin: 0 5px;
        }

        .accordion-toggle {
            width: calc(100% - 160px);
            display: inline-block;
        }

        .q-edits {
            display: inline-block;
        }

        .accordion .panel .panel-title .accordion-toggle {
            display: inline-block;
        }

    </style>
{% endblock css %}


{% block page_title %}
<div class='container' style='margin-bottom: 1em;'>
    <div class="page-title pull-left">
        <h1>{{ t_name }}
            <small>creation &amp; editing</small>
        </h1>
    </div>

    <div class="page-toolbar pull-right" style='padding-top: 2em'>
        <a href="{% url 'all-templates' %}" class="btn btn-long btn-primary pull-right">
            <i class="fa fa-chevron-left"></i>&nbsp;&nbsp;Back
        </a>
    </div>
</div>
{% endblock page_title %}


{% block main_content %}

    {% include "messages.html" %}

    <div id='app' class='container'>

    <straits-new-parent-sections>
    </straits-new-parent-sections>


    <straits-sections
        :sections='sections'
        ref='straitsSectionsComponent'
    >
    </straits-sections>

    <question-modal
        id = 'modal-question'
        :section      = 'section'
        :question     = 'question'
        :question-idx = 'questionIdx'
    ></question-modal>

    </div>

{% endblock main_content %}


{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script>'use strict';
axios.defaults.xsrfCookieName  = 'csrftoken';
axios.defaults.xsrfHeaderName  = 'X-CSRFTOKEN';
axios.defaults.withCredentials = true;

Vue.filter( 'limitTo', function( val, limit ){
  return ( val || '').substr( 0, limit );
});

// {% include 'question-modal/index.js' %}
// {% include 'edit_template/straits-new-parent-sections.js' %}
// {% include 'edit_template/straits-section-question.js' %}
// {% include 'edit_template/straits-sections.js' %}
// {% include 'edit_template/index.js' %}
</script>
{% endblock js %}

django/straits/templates/edit_template/straits-new-parent-sections.html
<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="row">


                <div class="col-md-7">

                    <div class="row">
                        <div class="col-md-8">
                            <h4>New Parent Sections</h4>
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-3">
                                        <input type="number" name="order" class="form-control" placeholder="Order">
                                    </div>
                                    <div class="col-md-9">
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="psection"
                                            placeholder="Enter Parent Section" required>
                                            <span class="input-group-btn">
                                                <button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i>&nbsp;&nbsp;Add
                                                </button>
                                            </span>
                                        </div>
                                        <!-- /input-group -->
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="row">
                        {% for s in psections %}
                        <div class="col-md-3 margin-top-20 text-center">
                            <h4>
                                <i class="fa fa-list fa-2x"></i></br>
                                <a href="#" class="psection" data-pk="{{ s.id }}" data-name="name"
                                data-url="#"
                                data-title="Edit Parent Section Name">{{ s.name }}</a></br>
                            </h4>
                            <h4 class="margin-top-20">
                                Order : <a href="#" data-type="number" class="psection" data-pk="{{ s.id }}"
                                data-name="order" data-url="#"
                                data-title="Edit Order">{{ s.order }}</a>
                            </h4>
                        </div>
                        {% endfor %}
                    </div>

                </div>


                <div class="col-md-5">

                    <h4>Version Control</h4>
                    <div class="row">
                        <div class="col-md-12">
                            <p>Templates published will not be editable and you'll need to create a new version.</p>
                            <select
                                name=""
                                id="vSel"
                                class="form-control"
                                @change='vSelChange()'
                                v-model='version'
                            >
                                {% for v in versions  %}
                                <option value="{{ v.order }}" {% if v.order == cversion.order %}selected{% endif %}>{{ v }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row margin-top-20">
                        <div class="col-md-12">
                            <button
                                class="btn btn-long btn-primary vBtn"
                                data-id="{{ t_id }}"
                                data-type="new"
                                @click='vBtnClick( "new", "{{ t_id }}" )'
                            >
                                <i class="fa fa-plus"></i>&nbsp;&nbsp;New Version
                            </button>

                            &nbsp;&nbsp;

                            {% if not cver.locked %}
                            <button
                                class="btn btn-long btn-primary vBtn"
                                data-type="publish"
                                data-id="{{ t_id }}"
                                @click='vBtnClick( "publish", "{{ t_id }}" )'
                            >
                                <i class="fa fa-lock"></i>&nbsp;&nbsp;Publish
                            </button>
                            {% endif %}
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>
</div>

django/straits/templates/edit_template/straits-section-question.html
{% verbatim %}
<div class="panel panel-default">

    <div class="panel-heading">
        <h4 class="panel-title" style="min-height:2em;">
            <a class="accordion-toggle accordion-toggle-styled collapsed"
                data-toggle="collapse"
                data-parent="#accordion3"
                :href="'#quest-' + question.id"
            >
                <strong>Q{{index + 1}}</strong> :
                {{ ( question.q_name || '' )|limitTo( 180 ) }}
                {{ ( question.q_name || '' ).length > 180 ? '...' : ''}}
                <br v-show="( question.q_name || '' ).length <= 80">
                <br v-show="( question.q_name || '' ).length <= 80">
                <br v-show="( question.q_name || '' ).length >= 90">
            </a>


            <div class="q-edits">

                <button
                    class="btn btn-danger pull-right"
                    :class="{disabled:!vpub}"
                    @click="!vpub||deleteQuestion()"
                    title='Delete'
                >
                    <i class="fa fa-times"></i>
                </button>

                <button
                    class="btn btn-warning btn-middle pull-right"
                    :class="{disabled:!vpub}"
                    @click="!vpub||editQuestion( question, true )"
                    title='Clone'
                >
                    <i class="fa fa-copy"></i>
                </button>

                <button
                    class="btn btn-primary pull-right"
                    :class="{disabled:!vpub}"
                    @click="editQuestion( question )"
                    title='Edit'
                >
                    <i class="fa fa-pencil"></i>
                </button>

            </div>
        </h4>
    </div> <!-- class="panel-heading" -->

    <div :id="'quest-' + question.id" class="panel-collapse collapse">
        <div class="panel-body">
            <p v-html="question.content"></p>

            <div class="row">
                <div class="col-md-4">
                    <p>
                        <strong>Action Plan Task</strong></br>
                        {{question.action_plan }}
                    </p>
                </div>
                <div class="col-md-4">
                    <p>
                        <strong>Dashboard Name</strong></br>
                        {{ question.d_name }}
                    </p>
                </div>
                <div class="col-md-4">
                    <p>
                        <strong>Weightage</strong></br>
                        {{ question.weightage }}
                    </p>
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-md-3" v-for="answer in question.answers">
                   <i class='fa fa-circle' :style='{color: getColor( answer.value )}'></i>
                   &nbsp;&nbsp;{{ answer.label }}
                </div>
            </div>
        </div>
    </div> <!-- class="panel-collapse -->

</div> <!-- class="panel" -->
{% endverbatim %}

django/straits/templates/edit_template/straits-sections.html
<div class="row" ng-app="temp-creation">
    <div class="col-md-12">

        {% verbatim %}
        <div class="row">
            <div class="col-sm-3">
                <ul class="nav nav-pills nav-stacked portlet light" data-tabs="tabs">

                    <li class="unsortable .">
                        <a href='#' @click="!vpub||addSectionTab()" :class="{disabled:!vpub}">
                            <i class="fa fa-plus"></i> New Sub Section
                        </a>
                    </li>

                    <li :class="{active: section.active}"
                        @click="activateSection(section)"
                        v-for="section in sections"
                    >
                        <a :href="'#tab-' + section.id" data-toggle="tab">
                            {{section.name}}
                        </a>
                    </li>

                </ul>
            </div>

            <div class="col-sm-9">
                <div class="tab-content">
                    <div
                        class="item tab-pane"
                        :class="{active: section.active}"
                        :id="'tab-' + section.id"
                        v-for="section in sections"
                    >
                        <div v-if="section.id == activeSection">
                            <div class="portlet light">
                                <div class="row">
                                    <div class="col-md-12">

                                        <form
                                            v-show="editorEnabled"
                                            @submit="updateSection(section)"
                                        >
                                            <div class="row">
                                                <div class="col-md-8">
                                                    <div id="div_id_name" class="form-group">
                                                        <label for="id_name" class="control-label requiredField">
                                                            Section Name<span class="asteriskField">*</span>
                                                        </label>

                                                        <div class="controls ">
                                                            <input class="textinput textInput form-control"
                                                                v-model="section.name" id="id_name"
                                                                maxlength="80" name="name" type="text">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div id="div_id_description" class="form-group">
                                                <label for="id_description" class="control-label ">
                                                    Description
                                                </label>

                                                <div class="controls ">
                                                    <textarea class="textarea form-control"
                                                            v-model="section.description"
                                                            cols="40" rows="10"
                                                            id="id_description" name="description"
                                                            redactor
                                                    ></textarea>
                                                </div>
                                            </div>

                                            <input type="hidden" name="section_id" :value="section.id">

                                            <div>
                                                <button
                                                    class="btn btn-danger btn-long pull-right"
                                                    @click="editorEnabled=!editorEnabled"
                                                >
                                                    <i class="fa fa-times"></i>&nbsp;&nbsp;Cancel
                                                </button>
                                                <button
                                                    class="btn btn-primary btn-long"
                                                    @click="editorEnabled=!editorEnabled">Save
                                                </button>
                                            </div>
                                        </form>

                                        <div ng-hide="editorEnabled">

                                            <div class="row">
                                                <div class="col-md-10">
                                                    <h3 class="s-title">
                                                        <strong>Section{{ section.order }}</strong> - {{ section.name }}
                                                    </h3>
                                                </div>
                                                <div class="col-md-2">
                                                    <button
                                                        class="btn btn-primary pull-right"
                                                        @click="editorEnabled=!editorEnabled"
                                                    >
                                                        <i class="fa fa-pencil"></i>
                                                    </button>
                                                </div>
                                            </div>

                                            <div class="row margin-top-20">
                                                <div class="col-md-12">
                                                    <p v-html="section.description"></p>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <button
                                                        class="btn btn-long btn-primary"
                                                        :class="{disabled:!vpub}"
                                                        @click="!vpub||newQuestion( section )"
                                                    >
                                                        <i class="fa fa-plus"></i>&nbsp;&nbsp;Add Question
                                                    </button>
                                                </div>
                                            </div>

                                        </div> <!-- ng-hide="editorEnabled" -->

                                    </div>
                                </div>
                            </div> <!-- class="portlet light" -->

                            <div my-sortable="questions" :sec="section.id" model="questions[section.id]">
                                <!-- track by question.id | orderBy:'order' -->
                                <div
                                    class="panel-group accordion"
                                    v-for="(question, index) in section.questions"
                                >
                                    <straits-section-question
                                        :question='question'
                                        :index='index'
                                        :section='section'
                                    ></straits-section-question>

                                </div> <!-- class="panel-group" -->
                            </div> <!-- my-sortable -->

                        </div> <!-- v-if="section.id == activeSection" -->

                    </div> <!-- class="tab-pane" -->
                </div> <!-- class="tab-content" -->
            </div>

            </div> <!-- col -->
        </div> <!-- row -->
        {% endverbatim %}

    </div>  <!-- col -->
</div>  <!-- row -->